on:
  push:
    branches:
      - master

name: Sync Amazon S3

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      
      - name: Sync Amazon S3 
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: "ap-northeast-1"
          FROM_PATH: "./psv-demo"
          DEST_PATH: ${{secrets.S3_UPLOAD_PATH}}
          OPTIONS: "--acl public-read --exact-timestamps --delete"